# Generated by Django 3.2.5 on 2024-02-01 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
        ('files', '0005_document_note_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='appointment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='consultations.appointment'),
        ),
        migrations.AddField(
            model_name='note',
            name='appointment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='consultations.appointment'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='appointment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='consultations.appointment'),
        ),
    ]
