# Generated by Django 3.2.5 on 2024-02-05 06:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_auto_20240201_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='appointment',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='prescribed_by',
        ),
        migrations.RemoveField(
            model_name='document',
            name='document_id',
        ),
        migrations.AddField(
            model_name='document',
            name='id',
            field=models.AutoField(auto_created=True,  primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='files.file'),
        ),
        migrations.DeleteModel(
            name='Note',
        ),
        migrations.DeleteModel(
            name='Prescription',
        ),
    ]
