# Generated by Django 3.2.5 on 2024-02-08 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0008_auto_20240206_0903'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
