# Generated by Django 3.2.5 on 2024-02-01 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_doctor_patient_pharmacyuser_remove_user_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
