# Generated by Django 3.2.5 on 2024-02-05 06:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_deleted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pharmacyuser',
            options={},
        ),
        migrations.AlterModelManagers(
            name='doctor',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='patient',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='pharmacyuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='online_consultation_capability',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='scr_access',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='user_ptr',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='user_ptr',
        ),
        migrations.RemoveField(
            model_name='pharmacyuser',
            name='user_ptr',
        ),
        migrations.AddField(
            model_name='doctor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pharmacyuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'SUPER_ADMIN'), ('DOCTOR', 'DOCTOR'), ('PATIENT', 'PATIENT'), ('PHARMACY_USER', 'PHARMACY_USER')], max_length=20),
        ),
    ]
