# Generated by Django 3.2.5 on 2024-02-06 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20240205_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useremailverification',
            name='code',
            field=models.PositiveIntegerField(),
        ),
    ]
