# Generated by Django 3.2.5 on 2024-02-06 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultations', '0003_auto_20240206_0903'),
        ('users', '0004_auto_20240205_1223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_type', models.CharField(max_length=50)),
                ('is_prescription_order_accepted', models.BooleanField()),
                ('notification_date', models.DateTimeField(auto_now_add=True)),
                ('preselected_pharmacy', models.CharField(max_length=10)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='consultations.appointment')),
                ('form_assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='consultations.formassessment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.patient')),
                ('prescription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='consultations.prescription')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charges_type', models.CharField(max_length=10)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
        ),
    ]
