# Generated by Django 3.2.5 on 2024-02-08 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0007_auto_20240208_0925'),
        ('users', '0010_auto_20240208_0925'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_invoice', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_appointment', to='consultations.appointment'),
        ),
        migrations.AlterField(
            model_name='order',
            name='form_assessment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_form_assessment', to='consultations.formassessment'),
        ),
        migrations.AlterField(
            model_name='order',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_orders', to='users.patient'),
        ),
        migrations.AlterField(
            model_name='order',
            name='prescription',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_prescription', to='consultations.prescription'),
        ),
    ]
