# Generated by Django 3.2.5 on 2024-02-09 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20240208_0925'),
        ('consultations', '0008_auto_20240209_1412'),
        ('orders', '0002_auto_20240208_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='consultations.appointment'),
        ),
        migrations.AlterField(
            model_name='order',
            name='form_assessment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='consultations.formassessment'),
        ),
        migrations.AlterField(
            model_name='order',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='users.patient'),
        ),
        migrations.AlterField(
            model_name='order',
            name='prescription',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='consultations.prescription'),
        ),
    ]
