# Generated by Django 3.2.5 on 2024-02-05 06:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20240205_1223'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_available', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='answer',
            name='answer_id',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='appointment_id',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='doctor_id',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='availability_id',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='doctor_id',
        ),
        migrations.RemoveField(
            model_name='formassessment',
            name='doctor_id',
        ),
        migrations.RemoveField(
            model_name='formassessment',
            name='form_assessment_id',
        ),
        migrations.RemoveField(
            model_name='formassessment',
            name='patient_id',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_id',
        ),
        migrations.AddField(
            model_name='answer',
            name='answered_date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='answer',
            name='id',
            field=models.BigAutoField(auto_created=True,  primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer',
            name='patient',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.patient'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.doctor'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='id',
            field=models.BigAutoField(auto_created=True,  primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='availability',
            name='doctor',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, to='users.doctor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='availability',
            name='id',
            field=models.BigAutoField(auto_created=True,  primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formassessment',
            name='doctor',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, related_name='form_assessment_doctor', to='users.doctor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formassessment',
            name='id',
            field=models.BigAutoField(auto_created=True,  primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formassessment',
            name='patient',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, related_name='form_assessment_patient', to='users.patient'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='patient',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.patient'),
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication', models.CharField(max_length=255)),
                ('dosage', models.CharField(max_length=100)),
                ('instructions', models.TextField()),
                ('prescribed_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='consultations.appointment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to='users.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='consultations.appointment')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_notes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
