# Generated by Django 3.2.5 on 2024-02-08 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20240208_0925'),
        ('vaccinations', '0003_auto_20240208_0925'),
        ('files', '0009_delete_document'),
        ('consultations', '0006_auto_20240207_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='form_assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_assessment_answers', to='consultations.formassessment'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_answers', to='users.patient'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_appointments', to='users.doctor'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_appointments', to='users.patient'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='consultations.appointment'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_availabilities', to='users.doctor'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='appointment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='appointment_notes', to='consultations.appointment'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_prescriptions', to='users.doctor'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='medicine',
            field=models.ManyToManyField(related_name='prescriptions', to='consultations.Medicine'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='pharmacy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_prescriptions', to='vaccinations.pharmacy'),
        ),
        migrations.AlterField(
            model_name='question',
            name='form_assessment',
            field=models.ManyToManyField(related_name='assessment_questions', to='consultations.FormAssessment'),
        ),
        migrations.AlterField(
            model_name='question',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_questions', to='users.patient'),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='appointment_documents', to='consultations.appointment')),
                ('file', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='document', to='files.file')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to='users.patient')),
            ],
        ),
    ]
