# Generated by Django 3.2.5 on 2024-02-09 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20240208_0925'),
        ('vaccinations', '0004_rename_pharmacy_user_pharmacy_owner'),
        ('consultations', '0007_auto_20240208_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='consultations.question'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='form_assessment',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='prescription', to='consultations.formassessment'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='form_assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='consultations.formassessment'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='users.patient'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='users.doctor'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='users.patient'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='users.doctor'),
        ),
        migrations.AlterField(
            model_name='formassessment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_assessments', to='users.doctor'),
        ),
        migrations.AlterField(
            model_name='formassessment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_assessments', to='users.patient'),
        ),
        migrations.AlterField(
            model_name='note',
            name='appointment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='consultations.appointment'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='appointment',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='prescription', to='consultations.appointment'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='users.doctor'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='pharmacy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='vaccinations.pharmacy'),
        ),
        migrations.AlterField(
            model_name='question',
            name='form_assessment',
            field=models.ManyToManyField(related_name='questions', to='consultations.FormAssessment'),
        ),
        migrations.AlterField(
            model_name='question',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='users.patient'),
        ),
    ]
