# Generated by Django 3.2.5 on 2024-02-12 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vaccinations', '0004_rename_pharmacy_user_pharmacy_owner'),
        ('consultations', '0008_auto_20240209_1412'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='SCR_consent',
            new_name='scr_consent',
        ),
        migrations.AddField(
            model_name='appointment',
            name='pharmacy',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='vaccinations.pharmacy'),
        ),
        migrations.AddField(
            model_name='formassessment',
            name='pharmacy',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='form_assessments', to='vaccinations.pharmacy'),
        ),
    ]
