# Generated by Django 3.2.5 on 2024-02-06 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccinations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='vaccine',
            field=models.ManyToManyField(to='vaccinations.Vaccine'),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='vaccine',
            field=models.ManyToManyField(to='vaccinations.Vaccine'),
        ),
    ]
