# Generated by Django 3.2.5 on 2024-02-08 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20240208_0925'),
        ('vaccinations', '0002_auto_20240206_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='pharmacy_user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy', to='users.pharmacyuser'),
        ),
        migrations.AlterField(
            model_name='country',
            name='vaccine',
            field=models.ManyToManyField(related_name='vaccine_countries', to='vaccinations.Vaccine'),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='vaccine',
            field=models.ManyToManyField(related_name='vaccine_pharmacies', to='vaccinations.Vaccine'),
        ),
    ]
