# Generated by Django 3.2.5 on 2024-02-09 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccinations', '0003_auto_20240208_0925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pharmacy',
            old_name='pharmacy_user',
            new_name='owner',
        ),
    ]
